import React from 'react';
import { GitPullRequest, Sparkles, CheckCircle2 } from 'lucide-react';
import { DocCodeBlock } from '../DocCodeBlock';
import { DocPagination } from '../DocPagination';

export interface DocCollaborationProps {
  onNavigateSection: (sectionId: string) => void;
}

export const DocCollaboration: React.FC<DocCollaborationProps> = ({ onNavigateSection }) => {
  return (
    <article className="space-y-12 animate-fade-in text-[#A1A1A1]">
      {/* Header */}
      <header className="space-y-3 border-b border-[#1F1F1F] pb-8">
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight text-[#FAFAFA]">
          Contributing Guide
        </h1>
        <p className="text-base text-[#A1A1A1] leading-relaxed max-w-2xl">
          Learn how to add new components and contribute to EasyUI. Because of our automated single source of truth engine, adding a component takes just two files and a few minutes.
        </p>
      </header>

      {/* The 2-File Rule */}
      <section className="p-5 rounded-xl border border-[#1F1F1F] bg-[#0E0E0E] space-y-3">
        <div className="flex items-center gap-2 text-[#FAFAFA] font-semibold text-sm">
          <Sparkles className="w-4 h-4 text-[#FAFAFA]" />
          <span>The Two-File Contribution Rule</span>
        </div>
        <p className="text-xs text-[#A1A1A1] leading-relaxed">
          When adding a component, you only ever create or touch two files in <code className="text-[#FAFAFA] font-mono bg-[#141414] border border-[#1F1F1F] px-1.5 py-0.5 rounded">src/components/ui/</code>:
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
          <div className="p-3.5 rounded-lg border border-[#1F1F1F] bg-[#141414] text-xs">
            <span className="text-[#FAFAFA] font-semibold block mb-1">1. Component (.tsx)</span>
            <span className="text-[#525252]">React + Tailwind CSS + Framer Motion implementation.</span>
          </div>
          <div className="p-3.5 rounded-lg border border-[#1F1F1F] bg-[#141414] text-xs">
            <span className="text-[#FAFAFA] font-semibold block mb-1">2. Metadata (.meta.ts)</span>
            <span className="text-[#525252]">Name, description, props documentation, and usage code.</span>
          </div>
        </div>
        <p className="text-[11px] text-[#6B6B6B]">
          All JSON endpoints, registry files, and website documentation pages are automatically generated by the engine.
        </p>
      </section>

      {/* Step 1: Scaffold */}
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <span className="w-6 h-6 rounded-full bg-[#141414] border border-[#1F1F1F] flex items-center justify-center text-[11px] font-mono font-bold text-[#FAFAFA]">
            1
          </span>
          <h2 className="text-lg font-semibold text-[#FAFAFA]">Scaffold a Starter Template</h2>
        </div>
        <p className="text-sm text-[#A1A1A1]">
          Use the built-in scaffolding command to generate starter boilerplate:
        </p>
        <DocCodeBlock
          code="npm run component:new TiltCard"
          language="bash"
          isTerminal={true}
        />
        <p className="text-xs text-[#6B6B6B]">
          This creates <code className="text-[#FAFAFA] font-mono">src/components/ui/TiltCard.tsx</code> and <code className="text-[#FAFAFA] font-mono">src/components/ui/TiltCard.meta.ts</code>.
        </p>
      </section>

      {/* Step 2: Implement Component */}
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <span className="w-6 h-6 rounded-full bg-[#141414] border border-[#1F1F1F] flex items-center justify-center text-[11px] font-mono font-bold text-[#FAFAFA]">
            2
          </span>
          <h2 className="text-lg font-semibold text-[#FAFAFA]">Write the Component Code</h2>
        </div>
        <p className="text-sm text-[#A1A1A1]">
          Write your React component using Framer Motion spring physics and clean Tailwind CSS styling:
        </p>

        <DocCodeBlock
          code={`import React, { useRef } from 'react';
import { motion, useSpring } from 'framer-motion';
import { cn } from '../../lib/utils';

export interface TiltCardProps extends React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode;
  maxTilt?: number;
  className?: string;
}

export const TiltCard: React.FC<TiltCardProps> = ({
  children,
  maxTilt = 15,
  className,
  ...props
}) => {
  const rotateX = useSpring(0, { stiffness: 300, damping: 25 });
  const rotateY = useSpring(0, { stiffness: 300, damping: 25 });

  return (
    <motion.div
      style={{ rotateX, rotateY, transformStyle: 'preserve-3d' }}
      className={cn('rounded-2xl border border-[#1F1F1F] bg-[#0E0E0E] p-6', className)}
      {...(props as any)}
    >
      {children}
    </motion.div>
  );
};`}
          language="tsx"
          title="src/components/ui/TiltCard.tsx"
        />
      </section>

      {/* Step 3: Define Metadata */}
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <span className="w-6 h-6 rounded-full bg-[#141414] border border-[#1F1F1F] flex items-center justify-center text-[11px] font-mono font-bold text-[#FAFAFA]">
            3
          </span>
          <h2 className="text-lg font-semibold text-[#FAFAFA]">Define Component Metadata</h2>
        </div>
        <p className="text-sm text-[#A1A1A1]">
          Define props, category, badges, and usage snippet in the metadata file:
        </p>

        <DocCodeBlock
          code={`import type { EasyComponentMeta } from '../../types/component';

export const TiltCardMeta: EasyComponentMeta = {
  id: 'tilt-card',
  name: 'Tilt Card',
  category: 'Motion',
  description: 'Tactile 3D perspective tilt card that tracks pointer momentum with springs.',
  badges: ['Framer Motion', '3D Perspective'],
  cliCommand: 'npx shadcn@latest add Surajmaurya1/easyui/tilt-card',
  dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
  files: ['src/components/ui/TiltCard.tsx'],
  props: [
    { name: 'children', type: 'React.ReactNode', required: true, description: 'Inner card contents' },
    { name: 'maxTilt', type: 'number', defaultValue: '15', description: 'Max rotation angle' },
  ],
  usageExample: \`<TiltCard maxTilt={20}>
  <p className="text-white">Hover to experience 3D tilt.</p>
</TiltCard>\`,
  sourceCode: '', // Automatically populated by sync script
};`}
          language="typescript"
          title="src/components/ui/TiltCard.meta.ts"
        />
      </section>

      {/* Step 4: Sync & Verify */}
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <span className="w-6 h-6 rounded-full bg-[#141414] border border-[#1F1F1F] flex items-center justify-center text-[11px] font-mono font-bold text-[#FAFAFA]">
            4
          </span>
          <h2 className="text-lg font-semibold text-[#FAFAFA]">Sync & Validate</h2>
        </div>
        <p className="text-sm text-[#A1A1A1]">
          Execute the sync and validation script to generate registry artifacts:
        </p>

        <DocCodeBlock
          code={`# Sync all components and metadata
npm run component:sync

# Validate all schemas and disk paths
npm run registry:validate`}
          language="bash"
          isTerminal={true}
        />
      </section>

      {/* PR Checklist */}
      <section className="p-5 rounded-2xl border border-[#1F1F1F] bg-[#0E0E0E] space-y-3">
        <div className="flex items-center gap-2">
          <GitPullRequest className="w-4 h-4 text-[#FAFAFA]" />
          <h2 className="text-sm font-semibold text-[#FAFAFA]">Pull Request Checklist</h2>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs">
          {[
            'Component is written in TypeScript (.tsx) with clean exports',
            'Corresponding .meta.ts is complete with props and usage',
            'npm run component:sync ran with 0 errors',
            'npm run registry:validate passed cleanly',
            'Spring motion feels smooth and responsive',
            'Accessible with keyboard and reduced-motion fallback',
          ].map((item, idx) => (
            <div key={idx} className="flex items-start gap-2 p-2.5 rounded-lg border border-[#1F1F1F] bg-[#141414]">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
              <span className="text-[#A1A1A1]">{item}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Pagination Footer */}
      <DocPagination currentTopic="collaboration" onNavigateTopic={onNavigateSection} />
    </article>
  );
};
